-- Replace leftover Vvveb demo content on Contact (7) and About (11) with real,
-- on-brand, styled Digital Sovereignty content (English, language_id = 1).
-- Services (12) was already seeded in db-apply.sql.
-- Target DB: supplierdemolead-vvvebapp-db-1 (the app's MySQL).

-- CONTACT (post_id 7): short styled intro shown above the lead form.
UPDATE post_content SET
  content = '<p style="color:var(--sd-muted);font-size:1.05rem;line-height:1.7;max-width:620px;">Whether you are scoping a sovereign cloud migration, preparing an audit, or simply weighing your options, our experts are here to help. Reach out and we will get back to you within 24 business hours.</p><div class="row g-3 mt-2"><div class="col-md-4"><div class="sd-card h-100"><h3 style="font-size:1rem;font-weight:700;margin-bottom:.35rem;">&#9993;&#65039; Email</h3><p style="margin:0;"><a href="mailto:contact@sovereignty.example">contact@sovereignty.example</a></p></div></div><div class="col-md-4"><div class="sd-card h-100"><h3 style="font-size:1rem;font-weight:700;margin-bottom:.35rem;">&#128222; Phone</h3><p style="margin:0;"><a href="tel:+442012345678">+44 20 1234 5678</a></p></div></div><div class="col-md-4"><div class="sd-card h-100"><h3 style="font-size:1rem;font-weight:700;margin-bottom:.35rem;">&#128205; Offices</h3><p style="margin:0;">London &middot; Paris &middot; Brussels &middot; Luxembourg</p></div></div></div>'
WHERE post_id = 7 AND language_id = 1;

-- ABOUT (post_id 11): mission + method + why-us cards + certifications.
UPDATE post_content SET
  content = '<p style="color:var(--sd-muted);font-size:1.15rem;line-height:1.7;max-width:720px;">We help European organizations regain control of their digital assets &mdash; combining sovereign cloud, data protection and pragmatic strategy so you stay compliant, secure and independent, without sacrificing performance.</p><h2 style="font-size:clamp(1.5rem,3vw,2rem);font-weight:800;letter-spacing:-.02em;margin:2.5rem 0 1.25rem;">A clear, proven method</h2><div class="row g-4"><div class="col-md-6 col-lg-3"><div class="sd-card h-100"><h3 style="font-size:1.05rem;font-weight:700;">1. Audit &amp; Mapping</h3><p>We map your data, workloads and regulatory exposure to find what truly needs sovereignty.</p></div></div><div class="col-md-6 col-lg-3"><div class="sd-card h-100"><h3 style="font-size:1.05rem;font-weight:700;">2. Tailored Strategy</h3><p>A roadmap aligned with your industry constraints, budget and existing tooling.</p></div></div><div class="col-md-6 col-lg-3"><div class="sd-card h-100"><h3 style="font-size:1.05rem;font-weight:700;">3. Implementation</h3><p>Migration and integration with reversibility guaranteed and no hidden lock-in.</p></div></div><div class="col-md-6 col-lg-3"><div class="sd-card h-100"><h3 style="font-size:1.05rem;font-weight:700;">4. Run &amp; Improve</h3><p>Ongoing monitoring, optimization and 24/7 support from our European teams.</p></div></div></div><h2 style="font-size:clamp(1.5rem,3vw,2rem);font-weight:800;letter-spacing:-.02em;margin:2.5rem 0 1.25rem;">Why organizations choose us</h2><div class="row g-4"><div class="col-md-4"><div class="sd-card h-100"><h3 style="font-size:1.05rem;font-weight:700;">European by design</h3><p>Data hosted and processed in Europe, GDPR-compliant end to end.</p></div></div><div class="col-md-4"><div class="sd-card h-100"><h3 style="font-size:1.05rem;font-weight:700;">Reversible &amp; open</h3><p>Open standards and portable formats &mdash; you are never locked in.</p></div></div><div class="col-md-4"><div class="sd-card h-100"><h3 style="font-size:1.05rem;font-weight:700;">Sector expertise</h3><p>Public sector, healthcare, finance, defense, energy and industry.</p></div></div></div><h2 style="font-size:clamp(1.5rem,3vw,2rem);font-weight:800;letter-spacing:-.02em;margin:2.5rem 0 1.25rem;">Certifications &amp; compliance</h2><p style="color:var(--sd-muted);">SecNumCloud &middot; ISO 27001 (InfoSec management) &middot; HDS (Healthcare data) &middot; GDPR (EU compliance) &middot; NIS2 (EU directive) &middot; SOC 2 Type II</p>'
WHERE post_id = 11 AND language_id = 1;
